// src/components/UsesFilterButton.tsx
import type { JSX } from 'react'
import { cn } from '@/utils/utils'

interface FilterButtonProps {
  active: boolean
  onClick: () => void
  children: React.ReactNode
}

export const UsesFilterButton = ({
  active,
  onClick,
  children,
}: FilterButtonProps): JSX.Element => {
  return (
    <button
      className={cn(
        'rounded-lg border px-4 py-2 text-sm transition-colors duration-200 ease-in-out',
        {
          'bg-primary text-white': active,
          'text-primary hover:bg-primary hover:text-white': !active,
        }
      )}
      onClick={onClick}
    >
      {children}
    </button>
  )
}

// src/components/Svelte/UsesFilterButton.svelte
<script lang="ts">
  import { cn } from '@/utils/utils';

  export let active: boolean;
</script>

<button
  class={cn(
    'rounded-lg border px-4 py-2 text-sm transition-colors duration-200 ease-in-out',
    {
      'bg-primary text-white': active,
      'text-primary hover:bg-primary hover:text-white': !active,
    }
  )}
  on:click
>
  <slot />
</button>
